CREATE TABLE T_Post (
    PostIdx BIGINT AUTO_INCREMENT PRIMARY KEY,
    UserIdx BIGINT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    ViewCount BIGINT DEFAULT 0,
    Status TINYINT DEFAULT 1,
    IsEdited BOOLEAN DEFAULT FALSE,
    RegDT DATETIME DEFAULT CURRENT_TIMESTAMP,
    DelDT DATETIME NULL,
    UpdateDT DATETIME DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_posts_user
        FOREIGN KEY (UserIdx)
        REFERENCES T_User(UserIdx)
        ON DELETE RESTRICT
)
-- FK, Transaction, Row Lock 지원
ENGINE=InnoDB
-- UTF-8, 이모지 지원
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;