CREATE TABLE rocket_factory.T_User (
    UserIdx BIGINT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(30) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,         -- 보안을 위해 해시된 비밀번호 저장(bcrypt)
    Nickname VARCHAR(50),
    Status TINYINT DEFAULT 1,
    RegDT DATETIME DEFAULT CURRENT_TIMESTAMP,
    DelDT DATETIME NULL,
    UpdateDT DATETIME DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

